### ISSUE TITLE
cli doesn't install latest?

### ISSUE THREAD

**Issue by DieterVanWerkum** [zurb/foundation-cli#110]
Hi,

Congrats on F 6.5.0. but when I bash $foundation new I still get v 6.4.3. (according to package-lock.json and yarn.lock). 

clues:
$ foundation update reports 'Nothing to update. You're good!'
bash $foundation watch does show the fancy aos.js powered demo menu.

I tried bash $npm update foundation-sites@latest (throws no errors but) doesn't change this.
node v6.14.4
npm v3.8.8

Best regards,
Dieter

**Comment by KnobCode** [comment]
I have the same question about this, I've been looking for any answer or information about it. My best guess is that, they might be just waiting for Foundation 7 in order to update the Foundation-CLI. 

One thing I haven't try is to install a template with out Foundation-CLI to see if works. Have you tried that yet?

**Comment by DieterVanWerkum** [comment]
Hi KnobCode,

No I didn't try that yet. I know it's an option to install legacy 
versions but would prefer if cli 'version 6' would load latest version 6.

Thanks for the pointer.

Best regards,
Dieter



Op 08-11-18 om 00:50 schreef KnobCode:
> I have the same question about this, I've been looking for any answer or information about it. My best guess is that, they might be just waiting for Foundation 7 in order to update the Foundation-CLI.
>
> One thing I haven't try is to install a template with out Foundation-CLI to see if works. Have you tried that yet?
>

**Comment by ncoden** [comment]
The Foundation CLI rely on `foundation-sites-template` and `foundation-zurb-template` to install `foundation-sites`. These 2 packages did not migrated to Foundation v6.5.0, but I will take care of this soon!

**Comment by benoitlemay** [comment]
It's done now.. but i got a problem when i build my project.. i got an JS error when i load my site.. But the "watch" process is working fine..
