### ISSUE TITLE
Foundation build failed (js file)

### ISSUE THREAD

**Issue by benoitlemay** [zurb/foundation-cli#111]
Hi!.. 

If i do foundation watch to work on my project everything is fine.. But if i do a foundation build.. When i open the website i got :

Uncaught TypeError: o(...)(...).foundation is not a function

 I'm using F6.5.1 with zurb template
using npm.. node 9.5.0

Installed via Foundation-cli  -> Zurb Templates.. 
Foundation watch -> OK
Foundation build -> when i run the web page i got "Uncaught TypeError: o(...)(...).foundation is not a function"

Even from fresh install..

**Comment by ncoden** [comment]
Hi @benoitlemay 👋,

Thank you for your issue. It should be resolved by https://github.com/zurb/foundation-zurb-template/pull/92.
