### ISSUE TITLE
Problem creating new app with foundation-cli EACCES ~/foundation-apps_3c7d8

### ISSUE THREAD

**Issue by osalama7** [zurb/foundation-cli#12]
I followed instructions listen on Zurb foundation website to install foundation on my Ubuntu 14.04 system.

I encountered the following error while running foundation-apps new myapp command it stops during installing dependencies, throws the following error.
Installing dependencies...

/usr/local/lib/node_modules/foundation-cli/node_modules/bower/node_modules/q/q.js:155
                throw e;
                      ^
Error: EACCES, open '/home/nautilus/.cache/bower/registry/bower.herokuapp.com/lookup/foundation-apps_3c7d8'

**Comment by jdivis** [comment]
I found that the lookup folder does not contain any folders, in my case.

**Comment by gakimball** [comment]
Hey, sorry for getting back to you so late! It looks like the CLI is failing on `bower install`. Can you try installing a project manually and see what happens?

```bash
git clone https://github.com/zurb/foundation-apps-template.git app
cd app
npm install
bower install
```

It might be an issue with how your system's Bower is configured, in which case you'll want to ask the [Bower folks](https://github.com/bower/bower/issues) for help.

**Comment by gakimball** [comment]
Going to close this out. I believe it's a problem with your Bower configuration, not the CLI. But if you still have trouble, you can follow the above steps to manually install a project.
