### ISSUE TITLE
foundation watch

### ISSUE THREAD

**Issue by kongpda** [zurb/foundation-cli#22]
I stuck on this when i run the `foundation watch`. Could you tell me how to fix this ?

![untitled-1](https://cloud.githubusercontent.com/assets/8193585/11954405/ce405e00-a8da-11e5-99ba-f88e46a6e14f.png)

**Comment by gakimball** [comment]
Does the process end or does it sit there? If it sits there, try editing a Sass file and see if it comes up `Starting 'sass'` again. That means the code is compiling.

**Comment by kongpda** [comment]
How long does it take ?

![untitled-1](https://cloud.githubusercontent.com/assets/8193585/11989420/669bca9a-aa2f-11e5-9a4b-8b7b7a538f35.png)

**Comment by jacmoe** [comment]
@kongpda The 'watch' command watches your files for changes and performs the specified action when it detects that changes happened.

So, how long does it take?

As long as you run it for.
If your machine runs forever, so does the watch command. ;)

**Comment by gakimball** [comment]
Yep, whenever you save a Sass file, you'll see this:

```
Starting 'sass'...
Finished 'sass' after 500ms
```

That means the compile worked.
