### ISSUE TITLE
"foundation new" was called with no arguments

### ISSUE THREAD

**Issue by neopostmodern** [zurb/foundation-cli#24]
As of Ubuntu 15.10 this app doesn't do... anything?
```
$ foundation new
ERROR: "foundation new" was called with no arguments
Usage: "foundation new"
```

When following the [official documentation](http://foundation.zurb.com/sites/docs/starter-projects.html) I get some fun errors too:
```
$ foundation new --framework sites --template zurb
ERROR: "foundation new" was called with arguments ["--framework", "sites", "--template", "zurb"]
Usage: "foundation new"

```

*Weird side note: I did a fresh install, but it says:*
```
$ foundation version
v1.0.4
```

**Comment by gakimball** [comment]
You still have the Foundation 5 CLI installed, and it's conflicting with the Foundation 6 CLI, which uses the same command name of `foundation`.

If you can live without the F5 CLI, run `gem uninstall foundation` to get rid of it. If you ever need it back, you can always run `gem install foundation` again. Note also that removing the F5 CLI won't prevent your F5 projects from running the same as they always have.

**Comment by neopostmodern** [comment]
Great, thanks! Any chance you could add a huuuuuge warning to the installation process, or even make it fail? Or is that outside of the possibilities `npm -g` gives you?

**Comment by gakimball** [comment]
It is possible, although post-install scripts have been known to crash on Windows, which is why we avoid them. *But* we can definitely look into it.

**Comment by gakimball** [comment]
Opened an issue here: zurb/foundation-cli#25
