### ISSUE TITLE
Interchange does not work when building a site for production

### ISSUE THREAD

**Issue by blixmbe** [zurb/foundation-cli#26]
I'm using interchange on some images.
It works when I use the watch command to assemble my site and run it on a test server.
However, when I build my site for production, using the 'foundation build' command, interchange does not work anymore.

**Comment by gakimball** [comment]
Do you get any JavaScript errors on the page?

**Comment by blixmbe** [comment]
No errors whatsoever. I did notice the menu has more styles when using the watch command.
E.g. <li>'s have an .dropdown.menu .is-dropdown-submenu-parent

**Comment by blixmbe** [comment]
The problem is that after a build for production, the src attribute isn't added dynamically.
No idea why, but it seems that UnCSS is breaking this functionality.
When I uncomment '.pipe(uncss)' in the gulpfile, interchange works as expected.

**Comment by gakimball** [comment]
@blixmbe What do you mean the `src` attribute isn't added dynamically?

**Comment by blixmbe** [comment]
@gakimball 
When I use the following code: 

    <img data-interchange="[http://placehold.it/150x150, small], [http://placehold.it/350x150, medium]">
I would expect that interchange adds the src attribute of an image to the specified path, like this

    <img data-interchange="[http://placehold.it/150x150, small], [http://placehold.it/350x150, medium]" src="http://placehold.it/150x150">

But, when using the build command, `src="http://placehold.it/150x150"` is not added.

**Comment by gakimball** [comment]
@blixmbe Run the full build with UnCSS and see if the rule `meta.foundation-mq` is in your compiled CSS.

**Comment by blixmbe** [comment]
Nope, it's not there.

**Comment by gakimball** [comment]
Strange, that rule is on the whitelist, see here: <https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.js#L110> Do you have that rule?

**Comment by blixmbe** [comment]
Yes, I do have that rule in my gulpfile

**Comment by gakimball** [comment]
Oh, got it! Can you change that rule to just `/.foundation-mq/` and see if that works?

**Comment by gakimball** [comment]
Or rather, `new RegExp('.foundation-mq')`

**Comment by blixmbe** [comment]
Adding `new RegExp('.foundation-mq')` fixed this issue.

**Comment by gakimball** [comment]
Awesome, thanks for helping us find that. :)

**Comment by moonweasel** [comment]
I am having this exact issue, where after running npm package, data interchange no longer works, with no src attribute being added. Unlike OP, there is no mention of .foundation-mq in my gulpfile…

**Comment by gakimball** [comment]
@moonweasel Are you using the [ZURB Template](https://github.com/zurb/foundation-zurb-template)?

**Comment by CrisWoler** [comment]
I have the same problem (only happens in Chrome). 
I downloaded the project from github but, I compiled the code with prepos. 
The src attribute isn't added dynamically with interchange. (in chrome, sometimes did it, sometimes did not). Any idea?
