### ISSUE TITLE
foundation update not working?

### ISSUE THREAD

**Issue by Kevinschmid86** [zurb/foundation-cli#28]
I have the latest cli version installed on my mac. Until today I had no issues with the cli commands regarding to the work with foundation sites. 
Now I want to update my existing project from the version 6.0.6 to the latest foundation sites version. Everytime when I use the foundation update command in my app folder the terminal says "Nothing to update. You´re good!" 

Has someone an idea what the problem could be?
If I create a new project I´ll get the newest version installed (current: 6.1.2)

Many thanks for an answer. 

With best regards

Kevin

**Comment by gakimball** [comment]
The version in your `bower.json` is something like `~6.0.6`. The `~` means "stay inside 6.0.x". So even if you run `foundation update`, Bower is preventing you from updating to 6.1.x.

These restrictions exist to keep developers from accidentally bumping minor version numbers, which introduce new features, and in some cases, deprecations which require migration.

If you're ready to update from 6.0.6 to 6.1.2, manually update the version number in `bower.json` and then run `foundation update`.

There might be a hook we can add to the CLI to streamline this. Right now `foundation update` literally just runs `bower update`, so it's beholden to Bower's logic.
