### ISSUE TITLE
foundation-cli broken on windows 10

### ISSUE THREAD

**Issue by weagle08** [zurb/foundation-cli#29]
when i try foundation new on windows 10 the arrow keys do nothing in allowing me to select site vs app.

version 2.0.2

**Comment by gakimball** [comment]
What shell do you use?

**Comment by weagle08** [comment]
windows command line... also tried with the git bash

**Comment by gakimball** [comment]
We're aware of an issue with some Windows command lines where you just can't use the arrow keys in command line tools period, so it's not something we can fix. However, you can also use the number keys to select items in the menu.

**Comment by phifa** [comment]
weird in powershell it works. but it should work in gitbash. number keys do not cut it for me. @weagle08 did you get it working?
