### ISSUE TITLE
"foundation new --framework site --template basic" failed

### ISSUE THREAD

**Issue by hoanguyen311** [zurb/foundation-cli#37]
I got this issue:

> foundation new --framework site --template basic
> ? What's the project called? (no spaces) first-foundation
> 
> ```
>         .
>        /|     ,
>   , /|/  \/| /|       Thanks for using ZURB Foundation for Site!
>  /|/       |/ |       -------------------------------------------
> ```
> 
>  |**_|            |**_|   Let's set up a new project.
>  _**|  ^^   ^^   |_**/   It shouldn't take more than a minute.
>      | -[O]--[O]- |
>      |    **_,    |
>      |    ...     |
>       _______**_/
> 
> Downloading the project template...There was an issue running git clone to download the Foundation for Apps template.
> Make sure your computer's Git is configured properly and then try again.

But it's ok when I ran **foundation new**

**Comment by timbaas** [comment]
Had the same issue when running `foundation new --framework emails`..

`foundation new` also works for me so thanks for pointing that out!

**Comment by adam-buckley** [comment]
Same issue here as well when trying to call `foundation new --framework email` (no 's' on "emails"). The CLI prompts for a project name then fails just as @hoanguyen311 describes. On OSX 10.10.

`$ foundation -v`
`Foundation CLI version 2.1.0`

`$ which git`
`/usr/bin/git`

**Comment by vikcon** [comment]
I had similar problem, just make sure you have your user assigned to folder/directory.
`sudo chown <user>:<user> -R <directory> `

Set permissions 755

`sudo chmod -R 755 <directory>`

Worked for me.
