### ISSUE TITLE
Foundation Zurb Template empty /scss folder gets copied into /dist folder

### ISSUE THREAD

**Issue by phifa** [zurb/foundation-cli#47]
Title says it all. Set up a new project, foundation new and foundation watch. The dist folder gets an empty scss folder, among all the other ones needed (css, js, etc.). Just a small bug, nothing big, just a bit annoying. can someone confirm? btw. i am on windows. 

see here
https://github.com/zurb/foundation-sites/issues/9851

**Comment by Deckluhm** [comment]
This is probably just an error since the `dist` directory should just contain precompiled / minified assets (CSS, JS, images, fonts...etc.).

SCSS files are in `src/assets/scss`.

**Comment by phifa** [comment]
Hey @Deckluhm i know, that is precisely why I posted the issue :)

**Comment by kball** [comment]
This is a bug in the template build system, relatively harmless, but the place to address it if you'd like is here: https://github.com/zurb/foundation-zurb-template/blob/master/config.yml#L23

The directory is being created during the copy task (https://github.com/zurb/foundation-zurb-template/blob/master/gulpfile.babel.js#L43) - you should be able to update the list of asset sources to exclude not only the contents of the scss directory but the directory itself.

Would accept a PR to this effect.

**Comment by phifa** [comment]
@kball i have no idea how to do a proper pull request. i cloned the repo, but then i had no way to transfer my commit to a pull request in this repo. Could you explain how to do this please? 

And I found the bug: 

My commit message: 
```
Bugfix for empty scss folder: 
This might be a bug in node, gulp or somewhere else. I changed one line
to make it work, this way, the folder itself and subfolders and files
are excluded properly.
```
In config.yml this line needs to be changed: 
`- "!src/assets/{img,js,scss}{,/**/*}"`

**Comment by kball** [comment]
@phifa To submit a pull request, make the change in a branch, then on github you can submit from that branch as a pull request. Here's a quick tutorial: https://yangsu.github.io/pull-request-tutorial/

**Comment by phifa** [comment]
@kball done: https://github.com/zurb/foundation-zurb-template/pull/57
