### ISSUE TITLE
ERROR installing Foundation-CLI on OS X 10.10.1

### ISSUE THREAD

**Issue by huseldusel** [zurb/foundation-cli#7]
This is the error message i get installing foundation-cli. Hope someone has an idea.

```
$ sudo npm install -g foundation-cli
/usr/local/bin/foundation-apps -> /usr/local/lib/node_modules/foundation-cli/bin/cli.js

> foundation-cli@1.0.4 postinstall /usr/local/lib/node_modules/foundation-cli
> node lib/welcome.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:838
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3
npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "foundation-cli"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.17
npm ERR! code ELIFECYCLE

npm ERR! foundation-cli@1.0.4 postinstall: `node lib/welcome.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the foundation-cli@1.0.4 postinstall script 'node lib/welcome.js'.
npm ERR! This is most likely a problem with the foundation-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/welcome.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-cli
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/penner/Documents/CloudStation/projects/Code/cms/public/npm-debug.log
```

**Comment by huseldusel** [comment]
Same Error after running that command.

**Comment by gakimball** [comment]
I see, I'll look into it further, then. In the mean time, you can install the template manually by following the [instructions on the readme](https://github.com/zurb/foundation-apps-template) for the template project. It's basically just a Git clone and then three install commands.

**Comment by ArtturiSipila** [comment]
sudo apt-get install nodejs-legacy  fixed it for me

**Comment by huseldusel** [comment]
I'm using OS X. So the command won't work.

**Comment by gakimball** [comment]
Do you typically have to install npm modules with `sudo`? Can you see if it would work without `sudo`?

Also, what did you use to install Node? Homebrew? The installer from the website?

**Comment by huseldusel** [comment]
I have to install all npm modules with ```sudo```, if i want them to be global. And I tried without ```sudo``` and without ```-g``` but I get a permission error.
I use the installer from the Node.js website.

**Comment by gakimball** [comment]
What error do you get when running `sudo npm install -g foundation-cli`?

**Comment by huseldusel** [comment]
'''sudo npm install -g foundation-cli
Password:
/usr/local/bin/foundation-apps -> /usr/local/lib/node_modules/foundation-cli/bin/cli.js

> foundation-cli@1.0.4 postinstall /usr/local/lib/node_modules/foundation-cli
> node lib/welcome.js

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Permission denied

node.js:838
    var cwd = process.cwd();
                      ^
Error: EACCES, permission denied
    at Function.startup.resolveArgv0 (node.js:838:23)
    at startup (node.js:58:13)
    at node.js:929:3

npm ERR! foundation-cli@1.0.4 postinstall: `node lib/welcome.js`
npm ERR! Exit status 8
npm ERR! 
npm ERR! Failed at the foundation-cli@1.0.4 postinstall script.
npm ERR! This is most likely a problem with the foundation-cli package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/welcome.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls foundation-cli
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "-g" "foundation-cli"
npm ERR! cwd /Users/penner
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0'''

**Comment by gakimball** [comment]
@huseldusel Could you try this?

```
sudo npm install -g foundation-cli --unsafe-perms
```

**Comment by huseldusel** [comment]
I left away the last 's' in your command like this:
```
sudo npm install -g foundation-cli --unsafe-perm
```
That worked for me. Thanks for help.
