### ISSUE TITLE
creating a new web project with foundation-cli

### ISSUE THREAD

**Issue by pedro1958** [zurb/foundation-cli#79]
I am creating a new web project with foundation-cli, when executing the necessary command the following error occurs:
C: \ Users \ xxxxxx \ AppData \ Roaming \ npm \ node_modules \ foundation-cli \ node_modules \ bower \ lib \ node_modules \ q \ q.js: 155
                 throw and;
                 ^
How do I solve it?
regards

**Comment by kball** [comment]
Hmm... I'm not seeing this... any Windows users that can take a look and see if you can reproduce? cc @zurb/yetinauts

**Comment by HarryBrand** [comment]
@pedro1958 @kball I have been having the same issue on Mac, when running "foundation new --framework sites --template basic". After updating to 2.2.3. 

Node - v6.4.0
Foundation CLI version 2.2.3

Error:
/usr/local/lib/node_modules/foundation-cli/node_modules/bower/lib/node_modules/q/q.js:155
                throw e;
                ^

jquery: Unable to find suitable version for jquery
    at createError (/usr/local/lib/node_modules/foundation-cli/node_modules/bower/lib/util/createError.js:4:15)

**Comment by kball** [comment]
hmm... ok thanks for the additional info, looking more

**Comment by kball** [comment]
@HarryBrand can you try again now? Traced it to a mismatch in the motion-ui jquery dependency as compared to the newer sites... should be resolved.

**Comment by HarryBrand** [comment]
@kball It is working now! Thank you

**Comment by kball** [comment]
Excellent.
