### ISSUE TITLE
jQuery not compiled

### ISSUE THREAD

**Issue by rabimx** [zurb/foundation-cli#84]
With foundation watch, the browser console returns this errors:
ReferenceError: jQuery is not defined  app.js:14497:1
TypeError: anchor.offset(...) is undefined app.js:20719:16
Any idea?

**Comment by kball** [comment]
Hi @rabimx can you give a bit more info to help figure this out? Is this a new project or an existing one? What are your versions of node and npm?

Thanks

**Comment by rabimx** [comment]
It's a new project that I created yesterday. My npm version is 5.1.0, node is v7.10.0 and foundation-cli is 2.2.3

**Comment by rabimx** [comment]
I updated the foundation project and the jquery error dissapeared, but the anchor.offset remains. I don't have idea what is the reference.

**Comment by rabimx** [comment]
Ok, I've seen the code and is a reference error in my html. closing the issue.

**Comment by kball** [comment]
Ok, thanks @rabimx
