### ISSUE TITLE
Foundation watch silent fail

### ISSUE THREAD

**Issue by jyulzz** [zurb/foundation-cli#93]
Hello,

After updating to the latest version of Foundation-cli (2.2.4), I am getting a silent failure when trying to run `foundation watch`.
`foundation build` seems unaffected and runs correctly as far as I can tell.

This happens both on existing projects I created before the update, and new projects created with the updated version of foundation-cli (2.2.4)

Any tips on how to get `foundation watch` back to working? Thanks!

**Comment by jyulzz** [comment]
Saved this by `npm update`.

**Comment by illiterati** [comment]
I can second this issue. Worked fine yesterday, updated to 2.2.4 today and it doesn't work.

**Comment by illiterati** [comment]
When I try `npm run watch` I get:

> npm ERR! missing script: watch

**Comment by illiterati** [comment]
Rolling back to 2.2.3 works.

**Comment by kball** [comment]
looking into this now

**Comment by kball** [comment]
This appears to have been accidentally introduced in https://github.com/zurb/foundation-cli/pull/66 and unnoticed at time of merge, we didn't publish an update until now. Fixing

**Comment by kball** [comment]
Fix published in 2.2.5. Thanks for the report!

**Comment by illiterati** [comment]
Thanks for the fast response!

**Comment by jyulzz** [comment]
Fixed in 2.5 yay 👍
